-- 1. Latest Trading Signal Per Stock
SELECT
    SYMBOL,
    DATE,
    CLOSE,
    MA20,
    MA50,
    SIGNAL
FROM MARKET_DATA.STOCK_PRICES
QUALIFY ROW_NUMBER() OVER (PARTITION BY SYMBOL ORDER BY DATE DESC) = 1;


-- 2. Average Return Per Stock
SELECT
    SYMBOL,
    ROUND(AVG(DAILY_RETURN) * 100, 2) AS AVG_RETURN_PERCENT
FROM MARKET_DATA.STOCK_PRICES
GROUP BY SYMBOL
ORDER BY AVG_RETURN_PERCENT DESC;


-- 3. Volatility Analysis
SELECT
    SYMBOL,
    ROUND(STDDEV(DAILY_RETURN), 5) AS VOLATILITY
FROM MARKET_DATA.STOCK_PRICES
GROUP BY SYMBOL
ORDER BY VOLATILITY DESC;


-- 4. Trading Signal Frequency
SELECT
    SYMBOL,
    SIGNAL,
    COUNT(*) AS SIGNAL_COUNT
FROM MARKET_DATA.STOCK_PRICES
GROUP BY SYMBOL, SIGNAL
ORDER BY SYMBOL;


-- 5. Latest Market Prices
SELECT
    SYMBOL,
    DATE,
    CLOSE
FROM MARKET_DATA.STOCK_PRICES
ORDER BY DATE DESC
LIMIT 20;
